dist: zesty

language: rust

rust:
    - stable

cache:
    cargo: true

addons:
    apt:
        - build-essential
        - pkg-config
        - libdrm-dev
        - clang

script:
    - cargo build
